-- H2-compatible version: use IDENTITY instead of BIGSERIAL (PostgreSQL syntax); no FK constraints.
CREATE TABLE notification_log (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT NOT NULL,
    task_id  BIGINT NOT NULL,
    channel  VARCHAR(16)  NOT NULL,
    status   VARCHAR(16)  NOT NULL,
    error    TEXT         NULL,
    message  TEXT         NULL,
    sent_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX notification_log_user_idx ON notification_log(user_id);
CREATE INDEX notification_log_task_idx ON notification_log(task_id);
